site_name: Texas Volunteer Caregiver in-a-box
site_url: https://jjasghar.github.io/texas-non-parent-caregiver-authorization-in-a-box
theme:
      name: material
repo_url: https://github.com/jjasghar/texas-non-parent-caregiver-authorization-in-a-box/
